baseURL: "https://sheetal-jadhav.github.io/sheetal_jadhav/"
title: Sheetal Jadhav
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Projects
          url: projects/
          weight: 2
        - name: Simulations
          url: simulations/
          weight: 3
        - name: Study Notes
          url: notes/
          weight: 4
        - name: Personal Essays
          url: essays/
          weight: 5 
        - name: Sci Comm.
          url: https://www.instagram.com/onlybrainytales/
          weight: 6

params:
    description: "This website hosts Sheetal Jadhav's research papers, course materials projects, curriculum vitae, and contact information."
    author: Moritz-Maria von Igelfeld
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Sheetal Jadhav
          subtitle: "I am a Professor in the Institute of Romance Philology at the University of Regensburg, Germany. My research focuses on Portuguese irregular verbs. I was a doctoral student of Professor Dr Dieter Vogelsang in Munich, and later a second assistant of Professor Walter Schoeffler-Henschell at the University of Wiesbaden."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          buttons:
            - name: Projects
              url: projects/
            - name: Simulations
              url: simulations/
            - name: Study Notes
              url: notes/
            - name: Personal Essays
              url: essays/
            - name: Sci Comm.
              url: https://www.instagram.com/onlybrainytales/

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:31jsheetal@gmail.com
        - name: Substack
          url: https://substack.com/@yoursthoughtfully?utm_campaign=profile&utm_medium=profile-page
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
        - name: GitHub
          url: https://github.com/sheetal-jadhav
        - name: Twitter
          url: https://x.com/_curiousneuron
        - name: Bluesky
          url: https://bsky.app/profile/thecuriousneuron.bsky.social
        - name: Location
          url: location/

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Moritz-Maria von Igelfeld"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
